# seed: 12350
seed: 12347
#
exportParams:
  exportFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/out/20230524_tests/sros_effect/indiv/danse_smallestSROs_2 # folder to export outputs
  onlySNRandESTOIinPlots: true
  sroEstimPerfPlot: false
  filters: false
  conditionNumberPlot: false
danseParams:
  performGEVD: false
  # performGEVD: true
  simType: batch
  # simType: batch_wola_estimation
  # simType: online
  nodeUpdating: asy
  # nodeUpdating: seq
  computeLocal: true
  computeCentralised: true
  # filterInitType: selectFirstSensor_andFixedValue
  filterInitType: selectFirstSensor
  filterInitFixedValue: 1
  #
  # ------------ SRO stuff
  # compensateSROs: true
  compensateSROs: false
  estimateSROs: Oracle   # "Oracle"/"CohDrift"/"DXCPPhaT"
  compensationStrategy: node-specific  # "node-specific"/"network-wide"
  # compensationStrategy: network-wide  # "node-specific"/"network-wide"
  # ----------------------
  #
  WOLAovlp: 0.5
  DFTsize: 1024
  startComputeMetricsAt: after_beginning_2nd_utterance_200
  t_expAvg50p: 30.
  t_expAvg50pExternalFilters: 30.
  # timeBtwExternalFiltUpdates: 1
  timeBtwExternalFiltUpdates: 0.25
  printoutsAndPlotting:
    printout_profiler: true
referenceSensor: 0
snrYlimMax: null
wasnParams:
  VADenergyDecrease_dB: 35
  VADwinLength: 0.04  # [s]
  rd: '[5, 5, 5]'
  minDistToWalls: 0.5
  sigDur: 15  # [s]
  selfnoiseSNR: 30  # [dB]
  # selfnoiseSNR: 999  # [dB]
  layoutType: random
  spinTop_randomWiggleAmount: 0.25  # [m]
  # t60: 0.2  # [s]
  t60: 0.0  # [s]
  # SROperNode: '[0, 100, 200]'  # [PPM]
  # SROperNode: '[0, 5, 10]'  # [PPM]
  SROperNode: '[10, 0, 5]'  # [PPM]
  # SROperNode: '[0]'  # [PPM]
  # nSensorPerNode: '[1, 2, 3]'
  nSensorPerNode: '[1, 1, 1]'
  interSensorDist: 0.05
  #
  baseSNR: 5
  desiredSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/01_speech/speech2.wav
  nDesiredSources: 1
  nNodes: 3
  nNoiseSources: 1
  noiseSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/02_noise/ssn/ssn_speech1.wav
  referenceSensor: 0
  vadFilesFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse\vad_files
  topologyParams:
    # topologyType: user-defined
    seed: 12347
    topologyType: fully-connected
    commDistance: 4.0
    plotTopo: false
    userDefinedTopo: '[[1, 1, 0], [1, 1, 1], [0, 1, 1]]'  # compact way to write lists