# seed: 12350
seed: 12347
#
exportParams:
  exportFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/out/20230512_tests/TIDANSEonline/test2_wExtUpEvery250ms # folder to export outputs
  onlySNRandESTOIinPlots: true
  sroEstimPerfPlot: false
  filters: false
  conditionNumberPlot: false
danseParams:
  noExternalFilterRelaxation: false
  # For debug
  performGEVD: false
  # performGEVD: true
  # simType: batch  # 'batch' or 'online'
  simType: online  # 'batch' or 'online'
  nodeUpdating: asy
  # nodeUpdating: seq
  computeLocal: true
  computeCentralised: true
  filterInitType: selectFirstSensor_andFixedValue
  filterInitFixedValue: 1
  #
  WOLAovlp: 0.5
  # WOLAovlp: 0.75
  DFTsize: 1024
  # DFTsize: 2048
  # DFTsize: 4096
  GEVDrank: 1
  startComputeMetricsAt: after_beginning_2nd_utterance_200
  t_expAvg50p: 30.
  t_expAvg50pExternalFilters: 30.
  # timeBtwExternalFiltUpdates: 1
  timeBtwExternalFiltUpdates: 0.25
  printoutsAndPlotting:
    printout_profiler: true
referenceSensor: 0
snrYlimMax: null
wasnParams:
  VADenergyDecrease_dB: 35
  VADwinLength: 0.04  # [s]
  rd: '[5, 5, 5]'
  minDistToWalls: 0.5
  # rd: '[0.05, 0.05, 0.05]'
  # rd: '[0.5, 0.5, 0.5]'
  # minDistToWalls: 0.0
  # Often used
  sigDur: 15  # [s]
  selfnoiseSNR: 30  # [dB]
  # selfnoiseSNR: 999  # [dB]
  # layoutType: random_spinning_top
  layoutType: random
  spinTop_randomWiggleAmount: 0.25  # [m]
  t60: 0.2  # [s]
  # t60: 0.0  # [s]
  SROperNode: '[0]'  # [PPM]
  # nSensorPerNode: '[1, 2, 3]'
  nSensorPerNode: '[1, 1, 1]'
  interSensorDist: 0.05
  #
  baseSNR: 5
  desiredSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/01_speech/speech2.wav
  nDesiredSources: 1
  nNodes: 3
  nNoiseSources: 1
  noiseSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/02_noise/ssn/ssn_speech1.wav
  referenceSensor: 0
  vadFilesFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse\vad_files
  topologyParams:
    topologyType: user-defined
    seed: 12347
    # topologyType: fully-connected
    commDistance: 4.0
    plotTopo: false
    userDefinedTopo: '[[1, 1, 0], [1, 1, 1], [0, 1, 1]]'  # compact way to write lists