seed: 0
#
exportParams:
  exportFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/out/20230911_tests/test1_Mk_2_2_1 # folder to export outputs
  metricsInPlots:
  - snr
  - sisnr
  - estoi
  sroEstimPerfPlot: false
  filters: false
  conditionNumberPlot: false
  mseBatchPerfPlot: false
danseParams:
  noFusionAtSingleSensorNodes: true
  startUpdatesAfterAtLeast: 0 # [s]
  maxBatchUpdates: 20
  performGEVD: true
  simType: online
  nodeUpdating: asy
  # nodeUpdating: seq
  noExternalFilterRelaxation: false
  computeLocal: true
  computeCentralised: true
  # computeLocal: false
  # computeCentralised: false
  filterInitType: selectFirstSensor
  covMatRandomInitScaling: 0  # <-- init SCMs as zeros
  use1stFrameAsBasis: true
  #
  WOLAovlp: 0.5
  DFTsize: 1024
  startComputeMetricsAt: after_beginning_2nd_utterance_200
  t_expAvg50p: 1
  t_expAvg50pExternalFilters: 1
  # forcedBeta: 0.98  # <-- if uncommented, bypasses `t_expAvg50p`
  forcedBetaExternalFilters: 0.7  # <-- if uncommented, bypasses `t_expAvg50pExternalFilters`
  timeBtwExternalFiltUpdates: 0.0
  covMatInitType: fully_random
  printoutsAndPlotting:
    printout_profiler: false
    printout_externalFilterUpdate: false
  # vvvvvvvvv Metrics vvvvvvvvv
  startComputeMetricsAt: after_15s
referenceSensor: 0  # Python-index of reference sensor in DANSE
snrYlimMax: null
wasnParams:
  trueRoom: true
  # Diffuse noise params
  diffuseNoise: false
  #
  VADenergyDecrease_dB: 40
  VADwinLength: 0.04  # [s]
  vadMinProportionActive: 0.25
  rd: '[5, 5, 5]'
  sigDur: 30  # [s]
  selfnoiseSNR: 15  # [dB]
  layoutType: random
  minDistToWalls: 0.5
  t60: 0.0  # [s]
  nNodes: 3
  # nSensorPerNode: '[1, 4]'
  nSensorPerNode: '[2, 2, 1]'
  SROperNode: '[0]'  # [PPM]
  interSensorDist: 0.05
  #
  snrBasis: at_mic_0
  snr: 5
  #
  signalType: from_file
  desiredSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse\tests\sigs\01_speech\speech2_16000Hz.wav
  nDesiredSources: 1
  nNoiseSources: 1
  noiseSignalFile: loadfrom danse/tests/sigs/02_noise/ssn
  referenceSensor: 0
  vadFilesFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse\vad_files