seed: 12348
#
exportParams:
  exportFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/out/20230503_tests/tmp_batch_wn  # folder to export outputs
danseParams:
  simType: batch  # 'batch' or 'online'
  maxBatchUpdates: 20
  startComputeMetricsAt: after_beginning_2nd_utterance_200
  t_expAvg50p: 10
  computeLocal: true
  computeCentralised: true
wasnParams:
  sigDur: 10  # [s]
  selfnoiseSNR: 30  # [dB]
  layoutType: random
  t60: 0.2  # [s]
  SROperNode: '[0]'  # [PPM]
  nNodes: 3
  nSensorPerNode: '[1, 2, 3]'
  interSensorDist: 0.05
  desiredSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/01_speech/speech1.wav
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/01_speech/speech2.wav
  # noiseSignalFile:
  # - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/02_noise/ssn/ssn_speech1.wav
  # - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/02_noise/ssn/ssn_speech2.wav
  noiseSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/02_noise/whitenoise_signal_1.wav
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/02_noise/whitenoise_signal_2.wav
  rd: '[5, 5, 5]'  # compact way to write lists/arrays (as a string)
  topologyParams:
    topologyType: fully-connected