seed: 0
#
exportParams:
  exportFolder: .\danse\out/20231020_tests/danse/oracle_scms/test1
  metricsInPlots:
  - snr
  - sisnr
  - estoi
  sroEstimPerfPlot: true
  conditionNumberPlot: false
  mseBatchPerfPlot: false
  bypassGlobalPickleExport: true  # if true, do not export the big outputs file for further post-processing
danseParams:
  stopUpdatesAfter: 300
  # winWOLAanalysisType: rect
  # winWOLAsynthesisType: rect
  noFusionAtSingleSensorNodes: true
  # noFusionAtSingleSensorNodes: false
  startUpdatesAfterAtLeast: 0 # [s]
  maxBatchUpdates: 20
  performGEVD: true
  # performGEVD: false
  simType: online
  # nodeUpdating: asy
  nodeUpdating: seq
  # noExternalFilterRelaxation: true
  noExternalFilterRelaxation: false
  computeLocal: true
  computeCentralised: true
  computeSingleSensorBroadcast: true
  # computeLocal: false
  # computeCentralised: false
  filterInitType: selectFirstSensor
  # filterInitType: random
  # filterInitType: fixedValue
  # filterInitFixedValue: 1
  # covMatRandomInitScaling: 0  # <-- init SCMs as zeros
  use1stFrameAsBasis: true  # <-- init SCMs using first available frame
  #
  WOLAovlp: 0.5
  DFTsize: 1024
  t_expAvg50p: 1
  t_expAvg50pExternalFilters: 1
  # forcedBeta: 0.98  # <-- if uncommented, bypasses `t_expAvg50p`
  forcedBetaExternalFilters: 0.7  # <-- if uncommented, bypasses `t_expAvg50pExternalFilters`. If == 0, no exp. averaging.
  timeBtwExternalFiltUpdates: 0
  # timeBtwExternalFiltUpdates: 0.5
  onlyBroadcastRefSensorSigs: false # /!\ /!\ /!\ /!\
  # timeBtwExternalFiltUpdates: 99999.
  covMatInitType: fully_random
  printoutsAndPlotting:
    printout_profiler: false
    printout_externalFilterUpdate: false
  # vvvvvvvvv Metrics vvvvvvvvv
  # startComputeMetricsAt: after_5s
  # startComputeMetricsAt: after_10s
  # startComputeMetricsAt: after_15s
  # startComputeMetricsAt: after_20s
  startComputeMetricsAt: after_200ms
  # vvvvvvvvv SRO-related vvvvvvvvv
  broadcastType: wholeChunk
  # broadcastType: fewSamples
  broadcastLength: 1   # for Ns=512, possible values: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
  # broadcastLength: 2
  efficientSpSBC: true
  # efficientSpSBC: false
  upTDfilterEvery: 1.
  #
  # compensateSROs: true
  compensateSROs: false
  includeFSDflags: false
  #
  estimateSROs: Oracle
  # estimateSROs: CohDrift
  compensationStrategy: node-specific
  cohDrift:
    alpha: 0.95
    segLength: 10
    estEvery: 1
    startAfterNups: 11
    estimationMethod: gs
    alphaRps: .05
    loop: open  # `open` == as in OJSP paper
referenceSensor: 0  # Python-index of reference sensor in DANSE
wasnParams:
  trueRoom: true
  # Diffuse noise params
  diffuseNoise: false
  diffuseNoisePowerFactor: 0.
  typeDiffuseNoise: noise
  #
  VADenergyDecrease_dB: 40
  VADwinLength: 0.04  # [s]
  vadMinProportionActive: 0.25
  rd: '[5, 5, 5]'
  # rd: '[.005, .005, .005]'
  # minDistToWalls: 0
  minDistToWalls: 0.5
  # interSensorDist: 0.0
  interSensorDist: 0.05
  sigDur: 10  # [s]
  # selfnoiseSNR: 999999999  # [dB]
  # selfnoiseSNR: 99  # [dB]
  # selfnoiseSNR: 60  # [dB]
  selfnoiseSNR: 15  # [dB]
  layoutType: random
  # layoutType: all_nodes_in_center
  # minDistToWalls: 0.5
  t60: 0.0  # [s]
  # nSensorPerNode: '[1, 1, 1]'
  # nSensorPerNode: '[1, 1, 1, 1]'
  # nSensorPerNode: '[5,5,5,5]'
  nSensorPerNode: '[2, 3]'
  # nSensorPerNode: '[1, 3, 2, 5]'
  # nSensorPerNode: '[2,2,2,2,2]'
  # nSensorPerNode: '[2, 1]'
  # nSensorPerNode: '[1, 1]'
  # nSensorPerNode: '[1, 4]'
  # nSensorPerNode: '[2, 2, 1]'
  # nSensorPerNode: '[1, 2, 3]'
  # nSensorPerNode: '[1, 2, 3, 4]'
  # nSensorPerNode: '[2, 2, 2, 2]'
  #
  snrBasis: at_mic_0
  snr: 5
  #
  SROperNode: '[0]'  # [PPM]
  # SROperNode: '[0, 40]'  # [PPM]
  # SROperNode: '[0, 200]'  # [PPM]
  # SROperNode: '[0, 100, 200]'  # [PPM]
  #
  # signalType: random
  signalType: from_file
  desiredSignalFile:
  - .\danse\tests\sigs\01_speech\speech2_16000Hz.wav
  nDesiredSources: 1
  nNoiseSources: 1
  # noiseSignalFile: loadfrom danse/tests/sigs/02_noise/ssn
  noiseSignalFile:
  - .\\danse\\tests\\sigs\\02_noise\\ssn\\ssn_3729-6852-0026.wav
  - .\\danse\\tests\\sigs\\02_noise\\ssn\\ssn_2830-3980-0002.wav
  referenceSensor: 0
  vadFilesFolder: .\danse\vad_files
  #
  topologyParams:
    # topologyType: user-defined
    topologyType: fully-connected
    commDistance: 4.0
    plotTopo: false
    seed: 12348
    userDefinedTopo: '[[1, 1, 0], [1, 1, 1], [0, 1, 1]]'
    # userDefinedTopo: '[[1, 1, 0, 0], [1, 1, 1, 0], [0, 1, 1, 1], [0, 0, 1, 1]]'
