seed: 0
#
exportParams:
  exportFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/out/20230907_tests/with_sqrthann/test4_tmp # folder to export outputs
  metricsInPlots:
  - snr
  - sisnr
  - estoi
  sroEstimPerfPlot: false
  filters: false
  conditionNumberPlot: false
  mseBatchPerfPlot: false
danseParams:
  startUpdatesAfterAtLeast: 0 # [s]
  maxBatchUpdates: 20
  performGEVD: true
  simType: online
  nodeUpdating: asy
  # nodeUpdating: seq
  noExternalFilterRelaxation: false
  computeLocal: true
  computeCentralised: true
  filterInitType: selectFirstSensor
  #
  WOLAovlp: 0.5
  DFTsize: 1024
  startComputeMetricsAt: after_beginning_2nd_utterance_200
  t_expAvg50p: 1
  t_expAvg50pExternalFilters: 1
  # forcedBeta: 0.98  # <-- if uncommented, bypasses `t_expAvg50p`
  forcedBetaExternalFilters: 0.99  # <-- if uncommented, bypasses `t_expAvg50pExternalFilters`
  timeBtwExternalFiltUpdates: 0.0
  covMatInitType: fully_random
  printoutsAndPlotting:
    printout_profiler: false
    printout_externalFilterUpdate: false
referenceSensor: 0  # Python-index of reference sensor in DANSE
snrYlimMax: null
wasnParams:
  trueRoom: true
  # Diffuse noise params
  diffuseNoise: false
  #
  VADenergyDecrease_dB: 40
  VADwinLength: 0.04  # [s]
  vadMinProportionActive: 0.25
  rd: '[5, 5, 5]'
  sigDur: 15  # [s]
  selfnoiseSNR: 15  # [dB]
  layoutType: random
  minDistToWalls: 0.5
  t60: 0.4  # [s]
  nNodes: 2
  nSensorPerNode: '[1, 4]'
  SROperNode: '[0, 0]'  # [PPM]
  interSensorDist: 0.05
  #
  baseSNR: 5
  signalType: from_file
  desiredSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse\tests\sigs\01_speech\speech2_16000Hz.wav
  nDesiredSources: 1
  nNoiseSources: 1
  noiseSignalFile: loadfrom danse/tests/sigs/02_noise/ssn
  referenceSensor: 0
  vadFilesFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse\vad_files