seed: 12348
#
exportParams:
  exportFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/out/20230504_tests/step/test1_newSpeech  # folder to export outputs
danseParams:
  # For debug
  saveConditionNumber: true
  saveConditionNumberEvery: 100  # [iterations]
  performGEVD: true
  # Often used
  simType: online  # 'batch' or 'online'
  nodeUpdating: asy
  computeLocal: true
  computeCentralised: true
  #
  DFTsize: 1024
  # DFTsize: 2048
  GEVDrank: 1
  startComputeMetricsAt: after_beginning_2nd_utterance_200
  t_expAvg50p: 10.
  t_expAvg50pExternalFilters: 2.
  timeBtwExternalFiltUpdates: 1.
referenceSensor: 0
snrYlimMax: null
wasnParams:
  # Often used
  sigDur: 15  # [s]
  selfnoiseSNR: 30  # [dB]
  # layoutType: random_spinning_top
  layoutType: random
  spinTop_randomWiggleAmount: 0.25  # [m]
  t60: 0.2  # [s]
  # t60: 0.0  # [s]
  SROperNode: '[0]'  # [PPM]
  nSensorPerNode: '[1, 2, 3]'
  interSensorDist: 0.05
  #
  baseSNR: 5
  desiredSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/01_speech/speech2.wav
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/01_speech/speech1.wav
  nDesiredSources: 1
  nNodes: 3
  nNoiseSources: 1
  noiseSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/02_noise/ssn/ssn_speech1.wav
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/02_noise/ssn/ssn_speech2.wav
  rd: '[5, 5, 5]'  # compact way to write lists/arrays (as a string)
  referenceSensor: 0
  topologyParams:
    topologyType: fully-connected