# Configuration file created during week 19 of 2023
# to conduct a series of benchmarking tests on my
# implementation of TI-GEVD-DANSE.
#
# See SOUNDS PhD research journal 2023, week 19, Monday. 

seed: 12350
#
exportParams:
  exportFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/out/20230507_tests/tigevddanse/beta10s/ssNodes_anechoic_noSROs # folder to export outputs
  onlySNRandESTOIinPlots: true
  sroEstimPerfPlot: false
  filters: false
  conditionNumberPlot: false
danseParams:
  # For debug
  # performGEVD: true
  performGEVD: false
  # simType: batch  # 'batch' or 'online'
  simType: online  # 'batch' or 'online'
  nodeUpdating: asy
  # nodeUpdating: seq
  computeLocal: true
  computeCentralised: true
  filterInitType: selectFirstSensor_andFixedValue
  # filterInitFixedValue: 0.01
  filterInitFixedValue: 1
  #
  WOLAovlp: 0.5
  # WOLAovlp: 0.75
  DFTsize: 1024
  # DFTsize: 2048
  # DFTsize: 4096
  GEVDrank: 1
  startComputeMetricsAt: after_beginning_2nd_utterance_200
  t_expAvg50p: 10.
  t_expAvg50pExternalFilters: 10.
  timeBtwExternalFiltUpdates: 0.25
  printoutsAndPlotting:
    printout_profiler: true
referenceSensor: 0
snrYlimMax: null
wasnParams:
  rd: '[5, 5, 5]'
  minDistToWalls: 0.5
  # rd: '[0.05, 0.05, 0.05]'
  # minDistToWalls: 0.0
  # SROperNode: '[0, 200, 400]'
  # SROperNode: '[0, 50, 100]'
  # SROperNode: '[0, 20, 40]'
  SROperNode: '[0, 0, 0]'
  sigDur: 15  # [s]
  selfnoiseSNR: 30  # [dB]
  # selfnoiseSNR: 999  # [dB]
  # layoutType: random_spinning_top
  layoutType: random
  spinTop_randomWiggleAmount: 0.25  # [m]
  # t60: 0.2  # [s]
  t60: 0.0  # [s]
  # nSensorPerNode: '[1, 2, 3]'
  nSensorPerNode: '[1, 1, 1]'
  interSensorDist: 0.05
  #
  baseSNR: 5
  desiredSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/01_speech/speech2.wav
  nDesiredSources: 1
  nNodes: 3
  nNoiseSources: 1
  noiseSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/02_noise/ssn/ssn_speech1.wav
  referenceSensor: 0
  topologyParams:
    topologyType: user-defined
    commDistance: 4.0
    plotTopo: false
    seed: 12348
    userDefinedTopo: '[[1, 1, 0], [1, 1, 1], [0, 1, 1]]'  # compact way to write lists
