seed: 12350
# seed: 12347
#
exportParams:
  exportFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/out/20230616_tests/sanityCheck_2nodes/3_tidanse_asy_w1  # folder to export outputs
  onlySNRandESTOIinPlots: true
  sroEstimPerfPlot: false
  filters: false
  conditionNumberPlot: false
danseParams:
  maxBatchUpdates: 30
  performGEVD: false
  # performGEVD: true
  # simType: batch
  simType: online
  nodeUpdating: asy
  # nodeUpdating: seq
  # noExternalFilterRelaxation: true
  noExternalFilterRelaxation: false
  computeLocal: true
  computeCentralised: true
  filterInitType: selectFirstSensor_andFixedValue
  # filterInitType: selectFirstSensor
  # filterInitFixedValue: 0.01
  filterInitFixedValue: 1
  #
  # ------------ SRO stuff
  # compensateSROs: true
  compensateSROs: false
  estimateSROs: Oracle   # "Oracle"/"CohDrift"/"DXCPPhaT"
  compensationStrategy: node-specific  # "node-specific"/"network-wide"
  # compensationStrategy: network-wide  # "node-specific"/"network-wide"
  # ----------------------
  #
  WOLAovlp: 0.5
  # DFTsize: 512
  DFTsize: 1024
  # DFTsize: 2048
  # DFTsize: 4096
  startComputeMetricsAt: after_beginning_2nd_utterance_200
  t_expAvg50p: 10
  t_expAvg50pExternalFilters: 10
  # forcedBeta: 0.98  # <-- if uncommented, bypasses `t_expAvg50p`
  # forcedBetaExternalFilters: 0.7  # <-- if uncommented, bypasses `t_expAvg50pExternalFilters`
  timeBtwExternalFiltUpdates: 0.25
  # timeBtwExternalFiltUpdates: 0.25
  printoutsAndPlotting:
    printout_profiler: false
referenceSensor: 0
snrYlimMax: null
wasnParams:
  # Diffuse noise params
  # diffuseNoise: true
  diffuseNoise: false
  diffuseNoisePowerFactor: -5
  # diffuseNoisePowerFactor: -9999
  # typeDiffuseNoise: noise
  typeDiffuseNoise: babble
  fileDiffuseBabble: danse/tests/sigs/02_noise/ssn/ssn_long.wav
  #
  # VADenergyDecrease_dB: 35
  VADenergyDecrease_dB: 50
  VADwinLength: 0.04  # [s]
  vadMinProportionActive: 0.25 
  rd: '[5, 5, 5]'
  minDistToWalls: 0.5
  sigDur: 15  # [s]
  selfnoiseSNR: 30  # [dB]
  # selfnoiseSNR: 999  # [dB]
  layoutType: random
  # layoutType: vert_spinning_top
  # layoutType: random_spinning_top
  # layoutType: predefined
  predefinedLayoutFile: danse/config_files/asc_layouts/asc2_20230613_174233.yaml
  spinTop_randomWiggleAmount: 0.1  # [m]
  t60: 0.2  # [s]
  # t60: 0.0  # [s]
  # SROperNode: '[0, 100, 200]'  # [PPM]
  # SROperNode: '[0, 5, 10]'  # [PPM]
  # SROperNode: '[10, 0, 5]'  # [PPM]
  SROperNode: '[0]'  # [PPM]
  # nSensorPerNode: '[1, 2, 3]'
  # nSensorPerNode: '[3, 3]'
  # nSensorPerNode: '[3, 3, 3]'
  nSensorPerNode: '[1, 1]'
  # nSensorPerNode: '[2, 2, 2]'
  interSensorDist: 0.2
  #
  baseSNR: 5
  # baseSNR: 20
  # baseSNR: 9999
  desiredSignalFile:
  - C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse/tests/sigs/01_speech/speech2_16000Hz.wav
  nDesiredSources: 1
  nNodes: 2
  nNoiseSources: 1
  noiseSignalFile: loadfrom danse/tests/sigs/02_noise/ssn
  referenceSensor: 0
  vadFilesFolder: C:\Users\pdidier\Dropbox\PC\Documents\sounds-phd\danse\vad_files
  topologyParams:
    topologyType: user-defined
    seed: 12347
    # topologyType: fully-connected
    commDistance: 4.0
    plotTopo: false
    # userDefinedTopo: '[[1, 1, 0], [1, 1, 1], [0, 1, 1]]'  # compact way to write lists
    userDefinedTopo: '[[1, 1], [1, 1]]'  # compact way to write lists